services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: isuports-3.t.isucon.dev
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      ISUCON_SQLITE_TRACE_FILE: /home/isucon/tmp/sqlite-trace.log
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
    init: true
